"""
Alembic migration script for creating doctor_notes table.
This file is a template for autogeneration.
"""
# This file will be generated by Alembic's autogenerate feature.
# To generate, run:
# python -m alembic revision --autogenerate -m "create_doctor_notes_table"

# Example (do not edit manually):
# def upgrade():
#     op.create_table(
#         'doctor_notes',
#         sa.Column('id', sa.Integer(), nullable=False),
#         ...
#     )
#
# def downgrade():
#     op.drop_table('doctor_notes')
