/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        "surface": "#131315",
        "surface-dim": "#131315",
        "surface-bright": "#39393b",
        "surface-container-lowest": "#0e0e10",
        "surface-container-low": "#1b1b1d",
        "surface-container": "#1f1f21",
        "surface-container-high": "#2a2a2b",
        "surface-container-highest": "#353436",
        "on-surface": "#e4e2e4",
        "on-surface-variant": "#c6c6cd",
        "inverse-surface": "#e4e2e4",
        "inverse-on-surface": "#303032",
        "outline": "#909097",
        "outline-variant": "#45464d",
        "surface-tint": "#bec6e0",
        "primary": "#bec6e0",
        "on-primary": "#283044",
        "primary-container": "#0f172a",
        "on-primary-container": "#798098",
        "inverse-primary": "#565e74",
        "secondary": "#d2bbff",
        "on-secondary": "#3f008e",
        "secondary-container": "#6001d1",
        "on-secondary-container": "#c9aeff",
        "tertiary": "#4cd7f6",
        "on-tertiary": "#003640",
        "tertiary-container": "#001b21",
        "on-tertiary-container": "#008da5",
        "error": "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        "primary-fixed": "#dae2fd",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed": "#131b2e",
        "on-primary-fixed-variant": "#3f465c",
        "secondary-fixed": "#eaddff",
        "secondary-fixed-dim": "#d2bbff",
        "on-secondary-fixed": "#25005a",
        "on-secondary-fixed-variant": "#5a00c6",
        "tertiary-fixed": "#acedff",
        "tertiary-fixed-dim": "#4cd7f6",
        "on-tertiary-fixed": "#001f26",
        "on-tertiary-fixed-variant": "#004e5c",
        "background": "#131315",
        "on-background": "#e4e2e4",
        "surface-variant": "#353436",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit-8": "2rem",
        "gutter": "24px",
        "container-max": "1440px",
        "unit-6": "1.5rem",
        "sidebar-collapsed": "72px",
        "unit-12": "3rem",
        "sidebar-width": "260px",
        "base": "4px",
        "unit-1": "0.25rem",
        "unit-4": "1rem",
        "unit-2": "0.5rem"
      },
      fontFamily: {
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Hanken Grotesk", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-md": ["Geist", "monospace"],
        "headline-md": ["Hanken Grotesk", "sans-serif"],
        "headline-lg": ["Hanken Grotesk", "sans-serif"],
        "display-lg": ["Hanken Grotesk", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "code-sm": ["Geist", "monospace"]
      }
    },
  },
  plugins: [],
}
