"""add_doctor_id_to_appointments

Revision ID: cb688c76ab3c
Revises: 7324a99617c7
Create Date: 2026-05-22 11:59:49.625592

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb688c76ab3c'
down_revision: Union[str, Sequence[str], None] = '7324a99617c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('slot_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'appointments', 'doctors', ['doctor_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'doctor_availability', ['slot_id'], ['id'])
    op.drop_column('appointments', 'doctor_name')
    op.drop_column('appointments', 'specialization')
    op.drop_column('appointments', 'appointment_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('specialization', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('doctor_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'slot_id')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
